# Kind集群配置 - Docker-only部署
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sical-cluster

# 网络配置
networking:
  # 禁用默认CNI，我们将使用自己的网络配置
  disableDefaultCNI: false
  # 设置Pod和Service的CIDR
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # API服务器端口
  apiServerPort: 6443

# 节点配置
nodes:
- role: control-plane
  # 端口映射配置
  extraPortMappings:
  # Kubernetes API服务器
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
  # HTTP Ingress
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # HTTPS Ingress
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # NodePort服务范围
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 32767
    hostPort: 32767
    protocol: TCP

# 特性门控
featureGates:
  # 启用一些有用的特性
  "EphemeralContainers": true
  "HPAScaleToZero": true

# 运行时配置
runtimeConfig:
  "api/all": "true"

# 集群配置
kubeadmConfigPatches:
- |
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      node-labels: "ingress-ready=true"
- |
  kind: KubeProxyConfiguration
  mode: "ipvs"
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
  controllerManager:
    extraArgs:
      "bind-address": "0.0.0.0"
  scheduler:
    extraArgs:
      "bind-address": "0.0.0.0"
  etcd:
    local:
      extraArgs:
        "listen-metrics-urls": "http://0.0.0.0:2381"